//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCSharp.Domains.FinanceDomain.Dtos.Resources {
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearningCSharp.Domains.FinanceDomain.Dtos.Resources.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string BankAccountDto_Title {
            get {
                return ResourceManager.GetString("BankAccountDto_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        public static string BankAccountDto_Id_Name {
            get {
                return ResourceManager.GetString("BankAccountDto_Id_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier for the bank account.
        /// </summary>
        public static string BankAccountDto_Id_Description {
            get {
                return ResourceManager.GetString("BankAccountDto_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID is required and cannot be empty.
        /// </summary>
        public static string BankAccountDto_Id_IsInvalid {
            get {
                return ResourceManager.GetString("BankAccountDto_Id_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string BankAccountDto_AccountNumber_Name {
            get {
                return ResourceManager.GetString("BankAccountDto_AccountNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account number assigned by the bank.
        /// </summary>
        public static string BankAccountDto_AccountNumber_Description {
            get {
                return ResourceManager.GetString("BankAccountDto_AccountNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number is required and must be between 8 and 20 characters.
        /// </summary>
        public static string BankAccountDto_AccountNumber_IsInvalid {
            get {
                return ResourceManager.GetString("BankAccountDto_AccountNumber_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Holder.
        /// </summary>
        public static string BankAccountDto_AccountHolder_Name {
            get {
                return ResourceManager.GetString("BankAccountDto_AccountHolder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name of the person who owns the account.
        /// </summary>
        public static string BankAccountDto_AccountHolder_Description {
            get {
                return ResourceManager.GetString("BankAccountDto_AccountHolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Holder name is required and must be between 2 and 100 characters.
        /// </summary>
        public static string BankAccountDto_AccountHolder_IsInvalid {
            get {
                return ResourceManager.GetString("BankAccountDto_AccountHolder_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Opened.
        /// </summary>
        public static string BankAccountDto_DateOpened_Name {
            get {
                return ResourceManager.GetString("BankAccountDto_DateOpened_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date when the account was first opened.
        /// </summary>
        public static string BankAccountDto_DateOpened_Description {
            get {
                return ResourceManager.GetString("BankAccountDto_DateOpened_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Opened is required and cannot be in the future.
        /// </summary>
        public static string BankAccountDto_DateOpened_IsInvalid {
            get {
                return ResourceManager.GetString("BankAccountDto_DateOpened_IsInvalid", resourceCulture);
            }
        }
    }
}
