//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCSharp.Domains.LogisticsDomain.Dtos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearningCSharp.Domains.LogisticsDomain.Dtos.Resources.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        internal static string Shipment_Title {
            get {
            return ResourceManager.GetString("Shipment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment ID.
        /// </summary>
        internal static string Shipment_Id_Name {
            get {
                return ResourceManager.GetString("Shipment_Id_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        internal static string Shipment_StreetAddress_Name {
            get {
                return ResourceManager.GetString("Shipment_StreetAddress_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suburb.
        /// </summary>
        internal static string Shipment_Suburb_Name {
            get {
                return ResourceManager.GetString("Shipment_Suburb_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Shipment_City_Name {
            get {
                return ResourceManager.GetString("Shipment_City_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Shipment_Region_Name {
            get {
                return ResourceManager.GetString("Shipment_Region_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string Shipment_PostalCode_Name {
            get {
                return ResourceManager.GetString("Shipment_PostalCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Shipment_Country_Name {
            get {
                return ResourceManager.GetString("Shipment_Country_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier for the shipment.
        /// </summary>
        internal static string Shipment_Id_Description {
            get {
                return ResourceManager.GetString("Shipment_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street number and name.
        /// </summary>
        internal static string Shipment_StreetAddress_Description {
            get {
                return ResourceManager.GetString("Shipment_StreetAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suburb or locality.
        /// </summary>
        internal static string Shipment_Suburb_Description {
            get {
                return ResourceManager.GetString("Shipment_Suburb_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City or town.
        /// </summary>
        internal static string Shipment_City_Description {
            get {
                return ResourceManager.GetString("Shipment_City_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region or province.
        /// </summary>
        internal static string Shipment_Region_Description {
            get {
                return ResourceManager.GetString("Shipment_Region_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        internal static string Shipment_PostalCode_Description {
            get {
                return ResourceManager.GetString("Shipment_PostalCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country (defaults to New Zealand).
        /// </summary>
        internal static string Shipment_Country_Description {
            get {
                return ResourceManager.GetString("Shipment_Country_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment ID is required and cannot be empty.
        /// </summary>
        internal static string Shipment_Id_IsInvalid {
            get {
                return ResourceManager.GetString("Shipment_Id_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address is required and must be between 5 and 100 characters.
        /// </summary>
        internal static string Shipment_StreetAddress_IsInvalid {
            get {
                return ResourceManager.GetString("Shipment_StreetAddress_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suburb is required and must be between 2 and 50 characters.
        /// </summary>
        internal static string Shipment_Suburb_IsInvalid {
            get {
                return ResourceManager.GetString("Shipment_Suburb_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required and must be between 2 and 50 characters.
        /// </summary>
        internal static string Shipment_City_IsInvalid {
            get {
                return ResourceManager.GetString("Shipment_City_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region is required and must be between 2 and 50 characters.
        /// </summary>
        internal static string Shipment_Region_IsInvalid {
            get {
                return ResourceManager.GetString("Shipment_Region_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code is required and must be exactly 4 digits.
        /// </summary>
        internal static string Shipment_PostalCode_IsInvalid {
            get {
                return ResourceManager.GetString("Shipment_PostalCode_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required and must be between 2 and 50 characters.
        /// </summary>
        internal static string Shipment_Country_IsInvalid {
            get {
                return ResourceManager.GetString("Shipment_Country_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        internal static string Carrier_Title {
            get {
                return ResourceManager.GetString("Carrier_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier ID.
        /// </summary>
        internal static string Carrier_Id_Name {
            get {
                return ResourceManager.GetString("Carrier_Id_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Carrier_Name_Name {
            get {
                return ResourceManager.GetString("Carrier_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        internal static string Carrier_TelephoneNumber_Name {
            get {
                return ResourceManager.GetString("Carrier_TelephoneNumber_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier for the carrier.
        /// </summary>
        internal static string Carrier_Id_Description {
            get {
                return ResourceManager.GetString("Carrier_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the carrier company.
        /// </summary>
        internal static string Carrier_Name_Description {
            get {
                return ResourceManager.GetString("Carrier_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number of the carrier.
        /// </summary>
        internal static string Carrier_TelephoneNumber_Description {
            get {
                return ResourceManager.GetString("Carrier_TelephoneNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier ID is required and cannot be empty.
        /// </summary>
        internal static string Carrier_Id_IsInvalid {
            get {
                return ResourceManager.GetString("Carrier_Id_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is required and must be between 2 and 100 characters.
        /// </summary>
        internal static string Carrier_Name_IsInvalid {
            get {
                return ResourceManager.GetString("Carrier_Name_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number is required and must be a valid NZ phone number.
        /// </summary>
        internal static string Carrier_TelephoneNumber_IsInvalid {
            get {
                return ResourceManager.GetString("Carrier_TelephoneNumber_IsInvalid", resourceCulture);
            }
        }
    }
}
