//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCSharp.Domains.LogisticsDomain.Dtos.Resources {
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearningCSharp.Domains.LogisticsDomain.Dtos.Resources.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        // ShipmentDto Resources
        public static string ShipmentDto_Title {
            get {
                return ResourceManager.GetString("ShipmentDto_Title", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Id_Name {
            get {
                return ResourceManager.GetString("ShipmentDto_Id_Name", resourceCulture);
            }
        }
        
        public static string ShipmentDto_StreetAddress_Name {
            get {
                return ResourceManager.GetString("ShipmentDto_StreetAddress_Name", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Suburb_Name {
            get {
                return ResourceManager.GetString("ShipmentDto_Suburb_Name", resourceCulture);
            }
        }
        
        public static string ShipmentDto_City_Name {
            get {
                return ResourceManager.GetString("ShipmentDto_City_Name", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Region_Name {
            get {
                return ResourceManager.GetString("ShipmentDto_Region_Name", resourceCulture);
            }
        }
        
        public static string ShipmentDto_PostalCode_Name {
            get {
                return ResourceManager.GetString("ShipmentDto_PostalCode_Name", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Country_Name {
            get {
                return ResourceManager.GetString("ShipmentDto_Country_Name", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Id_Description {
            get {
                return ResourceManager.GetString("ShipmentDto_Id_Description", resourceCulture);
            }
        }
        
        public static string ShipmentDto_StreetAddress_Description {
            get {
                return ResourceManager.GetString("ShipmentDto_StreetAddress_Description", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Suburb_Description {
            get {
                return ResourceManager.GetString("ShipmentDto_Suburb_Description", resourceCulture);
            }
        }
        
        public static string ShipmentDto_City_Description {
            get {
                return ResourceManager.GetString("ShipmentDto_City_Description", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Region_Description {
            get {
                return ResourceManager.GetString("ShipmentDto_Region_Description", resourceCulture);
            }
        }
        
        public static string ShipmentDto_PostalCode_Description {
            get {
                return ResourceManager.GetString("ShipmentDto_PostalCode_Description", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Country_Description {
            get {
                return ResourceManager.GetString("ShipmentDto_Country_Description", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Id_IsInvalid {
            get {
                return ResourceManager.GetString("ShipmentDto_Id_IsInvalid", resourceCulture);
            }
        }
        
        public static string ShipmentDto_StreetAddress_IsInvalid {
            get {
                return ResourceManager.GetString("ShipmentDto_StreetAddress_IsInvalid", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Suburb_IsInvalid {
            get {
                return ResourceManager.GetString("ShipmentDto_Suburb_IsInvalid", resourceCulture);
            }
        }
        
        public static string ShipmentDto_City_IsInvalid {
            get {
                return ResourceManager.GetString("ShipmentDto_City_IsInvalid", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Region_IsInvalid {
            get {
                return ResourceManager.GetString("ShipmentDto_Region_IsInvalid", resourceCulture);
            }
        }
        
        public static string ShipmentDto_PostalCode_IsInvalid {
            get {
                return ResourceManager.GetString("ShipmentDto_PostalCode_IsInvalid", resourceCulture);
            }
        }
        
        public static string ShipmentDto_Country_IsInvalid {
            get {
                return ResourceManager.GetString("ShipmentDto_Country_IsInvalid", resourceCulture);
            }
        }
        
        // CarrierDto Resources
        public static string CarrierDto_Title {
            get {
                return ResourceManager.GetString("CarrierDto_Title", resourceCulture);
            }
        }
        
        public static string CarrierDto_Id_Name {
            get {
                return ResourceManager.GetString("CarrierDto_Id_Name", resourceCulture);
            }
        }
        
        public static string CarrierDto_Name_Name {
            get {
                return ResourceManager.GetString("CarrierDto_Name_Name", resourceCulture);
            }
        }
        
        public static string CarrierDto_TelephoneNumber_Name {
            get {
                return ResourceManager.GetString("CarrierDto_TelephoneNumber_Name", resourceCulture);
            }
        }
        
        public static string CarrierDto_Id_Description {
            get {
                return ResourceManager.GetString("CarrierDto_Id_Description", resourceCulture);
            }
        }
        
        public static string CarrierDto_Name_Description {
            get {
                return ResourceManager.GetString("CarrierDto_Name_Description", resourceCulture);
            }
        }
        
        public static string CarrierDto_TelephoneNumber_Description {
            get {
                return ResourceManager.GetString("CarrierDto_TelephoneNumber_Description", resourceCulture);
            }
        }
        
        public static string CarrierDto_Id_IsInvalid {
            get {
                return ResourceManager.GetString("CarrierDto_Id_IsInvalid", resourceCulture);
            }
        }
        
        public static string CarrierDto_Name_IsInvalid {
            get {
                return ResourceManager.GetString("CarrierDto_Name_IsInvalid", resourceCulture);
            }
        }
        
        public static string CarrierDto_TelephoneNumber_IsInvalid {
            get {
                return ResourceManager.GetString("CarrierDto_TelephoneNumber_IsInvalid", resourceCulture);
            }
        }
    }
}
