//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCSharp.Domains.HumanResourcesDomain.Dtos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearningCSharp.Domains.HumanResourcesDomain.Dtos.Resources.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        // Employee Class Title
        internal static string Employee_Title {
            get {
                return ResourceManager.GetString("Employee_Title", resourceCulture);
            }
        }
        
        // Employee Properties
        internal static string Employee_Id_Name {
            get {
                return ResourceManager.GetString("Employee_Id_Name", resourceCulture);
            }
        }
        
        internal static string Employee_Id_Description {
            get {
                return ResourceManager.GetString("Employee_Id_Description", resourceCulture);
            }
        }
        
        internal static string Employee_EmployeeNumber_Name {
            get {
                return ResourceManager.GetString("Employee_EmployeeNumber_Name", resourceCulture);
            }
        }
        
        internal static string Employee_EmployeeNumber_Description {
            get {
                return ResourceManager.GetString("Employee_EmployeeNumber_Description", resourceCulture);
            }
        }
        
        internal static string Employee_FirstName_Name {
            get {
                return ResourceManager.GetString("Employee_FirstName_Name", resourceCulture);
            }
        }
        
        internal static string Employee_FirstName_Description {
            get {
                return ResourceManager.GetString("Employee_FirstName_Description", resourceCulture);
            }
        }
        
        internal static string Employee_LastName_Name {
            get {
                return ResourceManager.GetString("Employee_LastName_Name", resourceCulture);
            }
        }
        
        internal static string Employee_LastName_Description {
            get {
                return ResourceManager.GetString("Employee_LastName_Description", resourceCulture);
            }
        }
        
        internal static string Employee_Email_Name {
            get {
                return ResourceManager.GetString("Employee_Email_Name", resourceCulture);
            }
        }
        
        internal static string Employee_Email_Description {
            get {
                return ResourceManager.GetString("Employee_Email_Description", resourceCulture);
            }
        }
        
        internal static string Employee_JobTitle_Name {
            get {
                return ResourceManager.GetString("Employee_JobTitle_Name", resourceCulture);
            }
        }
        
        internal static string Employee_JobTitle_Description {
            get {
                return ResourceManager.GetString("Employee_JobTitle_Description", resourceCulture);
            }
        }
        
        internal static string Employee_Department_Name {
            get {
                return ResourceManager.GetString("Employee_Department_Name", resourceCulture);
            }
        }
        
        internal static string Employee_Department_Description {
            get {
                return ResourceManager.GetString("Employee_Department_Description", resourceCulture);
            }
        }
        
        internal static string Employee_HireDate_Name {
            get {
                return ResourceManager.GetString("Employee_HireDate_Name", resourceCulture);
            }
        }
        
        internal static string Employee_HireDate_Description {
            get {
                return ResourceManager.GetString("Employee_HireDate_Description", resourceCulture);
            }
        }
        
        internal static string Employee_Salary_Name {
            get {
                return ResourceManager.GetString("Employee_Salary_Name", resourceCulture);
            }
        }
        
        internal static string Employee_Salary_Description {
            get {
                return ResourceManager.GetString("Employee_Salary_Description", resourceCulture);
            }
        }
        
        internal static string Employee_IsActive_Name {
            get {
                return ResourceManager.GetString("Employee_IsActive_Name", resourceCulture);
            }
        }
        
        internal static string Employee_IsActive_Description {
            get {
                return ResourceManager.GetString("Employee_IsActive_Description", resourceCulture);
            }
        }
        
        // Employee Validation Messages
        internal static string Employee_Id_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_Id_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Employee_EmployeeNumber_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_EmployeeNumber_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Employee_FirstName_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_FirstName_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Employee_LastName_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_LastName_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Employee_Email_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_Email_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Employee_JobTitle_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_JobTitle_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Employee_Department_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_Department_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Employee_HireDate_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_HireDate_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Employee_Salary_IsInvalid {
            get {
                return ResourceManager.GetString("Employee_Salary_IsInvalid", resourceCulture);
            }
        }
        
        // Manager Class Title
        internal static string Manager_Title {
            get {
                return ResourceManager.GetString("Manager_Title", resourceCulture);
            }
        }
        
        // Manager Properties
        internal static string Manager_Id_Name {
            get {
                return ResourceManager.GetString("Manager_Id_Name", resourceCulture);
            }
        }
        
        internal static string Manager_Id_Description {
            get {
                return ResourceManager.GetString("Manager_Id_Description", resourceCulture);
            }
        }
        
        internal static string Manager_ManagerNumber_Name {
            get {
                return ResourceManager.GetString("Manager_ManagerNumber_Name", resourceCulture);
            }
        }
        
        internal static string Manager_ManagerNumber_Description {
            get {
                return ResourceManager.GetString("Manager_ManagerNumber_Description", resourceCulture);
            }
        }
        
        internal static string Manager_FirstName_Name {
            get {
                return ResourceManager.GetString("Manager_FirstName_Name", resourceCulture);
            }
        }
        
        internal static string Manager_FirstName_Description {
            get {
                return ResourceManager.GetString("Manager_FirstName_Description", resourceCulture);
            }
        }
        
        internal static string Manager_LastName_Name {
            get {
                return ResourceManager.GetString("Manager_LastName_Name", resourceCulture);
            }
        }
        
        internal static string Manager_LastName_Description {
            get {
                return ResourceManager.GetString("Manager_LastName_Description", resourceCulture);
            }
        }
        
        internal static string Manager_Email_Name {
            get {
                return ResourceManager.GetString("Manager_Email_Name", resourceCulture);
            }
        }
        
        internal static string Manager_Email_Description {
            get {
                return ResourceManager.GetString("Manager_Email_Description", resourceCulture);
            }
        }
        
        internal static string Manager_ManagementLevel_Name {
            get {
                return ResourceManager.GetString("Manager_ManagementLevel_Name", resourceCulture);
            }
        }
        
        internal static string Manager_ManagementLevel_Description {
            get {
                return ResourceManager.GetString("Manager_ManagementLevel_Description", resourceCulture);
            }
        }
        
        internal static string Manager_Department_Name {
            get {
                return ResourceManager.GetString("Manager_Department_Name", resourceCulture);
            }
        }
        
        internal static string Manager_Department_Description {
            get {
                return ResourceManager.GetString("Manager_Department_Description", resourceCulture);
            }
        }
        
        internal static string Manager_DirectReportsCount_Name {
            get {
                return ResourceManager.GetString("Manager_DirectReportsCount_Name", resourceCulture);
            }
        }
        
        internal static string Manager_DirectReportsCount_Description {
            get {
                return ResourceManager.GetString("Manager_DirectReportsCount_Description", resourceCulture);
            }
        }
        
        internal static string Manager_ManagementStartDate_Name {
            get {
                return ResourceManager.GetString("Manager_ManagementStartDate_Name", resourceCulture);
            }
        }
        
        internal static string Manager_ManagementStartDate_Description {
            get {
                return ResourceManager.GetString("Manager_ManagementStartDate_Description", resourceCulture);
            }
        }
        
        internal static string Manager_Salary_Name {
            get {
                return ResourceManager.GetString("Manager_Salary_Name", resourceCulture);
            }
        }
        
        internal static string Manager_Salary_Description {
            get {
                return ResourceManager.GetString("Manager_Salary_Description", resourceCulture);
            }
        }
        
        internal static string Manager_IsActive_Name {
            get {
                return ResourceManager.GetString("Manager_IsActive_Name", resourceCulture);
            }
        }
        
        internal static string Manager_IsActive_Description {
            get {
                return ResourceManager.GetString("Manager_IsActive_Description", resourceCulture);
            }
        }
        
        // Manager Validation Messages
        internal static string Manager_Id_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_Id_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_ManagerNumber_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_ManagerNumber_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_FirstName_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_FirstName_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_LastName_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_LastName_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_Email_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_Email_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_ManagementLevel_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_ManagementLevel_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_Department_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_Department_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_DirectReportsCount_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_DirectReportsCount_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_ManagementStartDate_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_ManagementStartDate_IsInvalid", resourceCulture);
            }
        }
        
        internal static string Manager_Salary_IsInvalid {
            get {
                return ResourceManager.GetString("Manager_Salary_IsInvalid", resourceCulture);
            }
        }
    }
}
